feat: init `@sheepdog/vanilla`
mainmatter/sheepdog pull request #253
Opened 2024-12-13 18:07 UTC by paoloricciuti

This initialize `@sheepdog/vanilla`

So, i think i've almost finished the vanilla version (i still need to write all the tests tho)...I'm a bit puzzled by a couple of things:
1. those are the events that i've defined
```ts
type Events =
	| 'error'
	| 'finish'
	| 'cancel'
	| 'instance-create'
	| 'instance-start'
	| 'instance-complete';

type InstanceEvents = 'error' | 'finish' | 'cancel' | 'start' | 'success';
```
for instance i think it makes perfect sense...you get an event for each state (minus isRunning but you can infer that with a couple of events)
I'm, not super convinced about the ones for the task...technically also error ,finish and cancel should have the prefix instance- because at the end of the day it's one of the instances that is erroring, or starting or etc etc. so maybe it might make sense to just drop instance- everywhere?
3. do you think we should pass something to the events? Like if you do
```ts
const my_task = task(...);

my_task.on("error", (/*do you need something here?*/)=>{

});

const performed = my_task.perform();

performed.on("error", (/*what about here?*/)=>{

});
```
4. the task function is returning an object which resembles the store we are returning from svelte...but it's just an object. The idea is that since it's the same reference if you use it in an even listener it will be updated when you read the value. What do you think about it?

I think we need to bikeshed it a bit and try to build something with it to get the feel but i'd say i'm pretty happy with the result

2025-02-28 14:27 UTC, nickschot requested changes
Looks good to me code wise, great job on the tests!

I might want to try (or at least see?) something running with it a bit but I can't spot any problems yet.

2025-02-28 14:27 UTC, nickschot commented on packages/vanilla/src/task.ts
> +					// not founding the instance in case of a syncronous
```suggestion
					// not finding the instance in case of a synchronous
```

This is what I assume is supposed to be here 😬 please do check.

2025-02-28 14:27 UTC, nickschot commented on packages/vanilla/src/task.ts
> +				if (instance) {
Is the instance not being there an actual possibility or is this to please TS? If it's the former, what does that mean for the rest of the code?

(this is also true for the other `on*` handlers of course)

2025-02-28 14:27 UTC, nickschot commented on packages/vanilla/tests/task.test.ts
> +		it("doesn't runs to completion if it's cancelled, the function is a generator and there's a yield after every await", async () => {
```suggestion
		it("doesn't run to completion if it's cancelled, the function is a generator and there's a yield after every await", async () => {
```

2025-02-28 14:38 UTC, paoloricciuti commented on packages/vanilla/src/task.ts
> +					// not founding the instance in case of a syncronous
It is lol

2025-02-28 14:42 UTC, paoloricciuti commented on packages/vanilla/src/task.ts
> +				if (instance) {
I can't exactly remember but i'm pretty sure it is only to please TS...we are deleting instances on instance cancel, on error and on instance complete but in all three cases there's no way we invoke the others.

What do you mean by "the rest of the code"?

2025-03-07 09:25 UTC, nickschot approved these changes

2025-03-07 09:28 UTC, merged